FROM    python:3.12-slim

LABEL warning="Run as Root"
WORKDIR /app

COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

COPY app.py .

# KEIN USER Statement = läuft als root!

EXPOSE 8080

CMD ["python", "app.py"]
