FROM python:3.12-slim-bookworm

LABEL maintainer="Michael Lindner"
LABEL security.scan="passed"

WORKDIR /app
COPY requirements-secure.txt req.txt
RUN pip install --no-cache-dir -r req.txt

RUN useradd  -r -s /bin/false appuser
USER appuser

COPY app.py .

EXPOSE 5000
HEALTHCHECK --interval=30s --timeout=3s \
        CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')" || exit 1

CMD ["python", "app.py"]

