services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "80"
    networks:
      frontend_net:
        ipv4_address:  192.168.2.2
        ipv6_address: fd00:cafe:beef::2
      backend_net:
        ipv4_address: 10.20.0.3
        ipv6_address: fd00:dead:beef::3
    
    
    volumes:
      - frontend_log:/var/log/nginx
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - backend
    restart:  unless-stopped
  backend:
    build: ./backend
    container_name: backend
    expose:
      - "5000"
    networks:
      backend_net:
        ipv4_address: "10.20.0.4"
        ipv6_address: "fd00:dead:beef::4"
    volumes:
      - backend_data:/app/data
      - backend_log:/app/logs
    restart:  unless-stopped
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro
      - proxy_log:/var/log/nginx
    restart:  unless-stopped
    networks:
      backend_net:
        ipv4_address: "10.20.0.5"
        ipv6_address: "fd00:dead:beef::5"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    expose:
      - "9090"
    volumes:
      - ./monitor/monitor.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      backend_net:
        ipv4_address: "10.20.0.6"
        ipv6_address: "fd00:dead:beef::6"
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    expose:
      - "3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SERVER_ROOT_URL=https://mth-dell04/monitor
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
      - GF_SECURITY_COOKIE_SAMESITE=none
      - GF_SECURITY_COOKIE_SECURE=true
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards
    networks:
      backend_net:
        ipv4_address: "10.20.0.7"
        ipv6_address: "fd00:dead:beef::7"
    restart: unless-stopped
volumes:
  grafana-data:
  backend_data:
  backend_log:
  frontend_data:
  frontend_log:
  proxy_log:

networks:
  frontend_net:
    driver: bridge
    enable_ipv6: true
    ipam: 
      config:
        - subnet: "192.168.2.0/24"
          gateway: "192.168.2.1"
        - subnet: "fd00:cafe:beef::/64"
          gateway: "fd00:cafe:beef::1"

  backend_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      config:
        - subnet: "10.20.0.0/24"
          gateway: "10.20.0.1"
        - subnet: "fd00:dead:beef::/64"
          gateway: "fd00:dead:beef::1"

