FROM python:3.11-slim

LABEL maintainer="training@example.com"
LABEL trivy.scan="demo"

WORKDIR /app

# Dependencies
COPY req.txt .
RUN pip install --no-cache-dir -r req.txt

# Non-root User
RUN useradd -r -s /bin/false -u 1001  appuser

# App kopieren
COPY app.py .

# Besitzer ändern
RUN chown -R appuser:appuser /app

USER appuser

EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=3s \
    CMD python -c "import urllib.request; urllib.request.urlopen('http://localhost:5000/health')" || exit 1

CMD ["python", "app.py"]
