events{}
http {
    upstream backend {
        server backend:5000;
    }
    upstream frontend {
        server frontend:80;
    }

    server{
        #listen 80;
        listen 443 ssl;
        ssl_certificate /etc/nginx/certs/nginx.crt;
        ssl_certificate_key /etc/nginx/certs/nginx.key;

        server_name mth-dell04;
        location / {
            proxy_pass http://frontend;
        }
        location /api {
            proxy_pass http://backend;
        }
    }

}